name: Deploy Nodejs Service

on:

  push:
    branches: ["main"]
    paths:
      - 'nodejs-docker-deployment/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd nodejs-docker-deployment/
          docker build -t nodejs-service .

      - name: Save image as tar
        run: docker save nodejs-service | gzip > node-service.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: nodejs-service.tar.gz
          target: /home/ubuntu/

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < /home/ubuntu/node-service.tar.gz
            docker stop node-service || true
            docker rm node-service || true
            docker run -d --name nodejs-service -p 3000:3000 \
              -e SECRET_MESSAGE=${{ secrets.SECRET_MESSAGE }} \
              -e USERNAME=${{ secrets.APP_USERNAME }} \
              -e PASSWORD=${{ secrets.APP_PASSWORD }} \
              nodejs-service
